apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
    - name: app
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: app-vol
  volumes:
    - name: app-vol
      persistentVolumeClaim:
        claimName: pod-pvc