apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: confluence-storage
spec:
  storageClassName: ebsstorage
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 10Gi