apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: EKStestcluster1
  region: us-east-1

nodeGroups:
  - name: eksnodegroup
    instanceType: t3.medium
    desiredCapacity: 3
    ssh: # use existing EC2 key
      publicKeyName: eks-key

cloudWatch:
  clusterLogging:
    enableTypes: ["all"]
    