apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: EKS-test-cluster2
  region: us-east-1

nodeGroups:
  - name: eks-dev-ng
    instanceType: t3.medium
    desiredCapacity: 5
    ssh: # use existing EC2 key
      publicKeyName: eks-key

cloudWatch:
  clusterLogging:
    enableTypes: ["all"]
    